name: install-swig-r-windows
description: "Install the customized SWIG used for swigex0 R package under windows"
runs:
  using: "composite"
  steps:
  - name: Install SWIG dependencies
    # See nuget.yml in SWIG github repo
    shell: powershell
    run: |
        nuget install Bison -Version 3.7.4 -OutputDirectory ${{env.BISON_ROOT}}
        nuget install PCRE2 -Version 10.39 -OutputDirectory ${{env.PCRE2_ROOT}}

  - name: Compile and install [customized] SWIG 4.2.0b
    shell: powershell
    # TODO : Use a tagged realease (not the master branch)
    run: |
      mkdir swig_src
      cd swig_src
      git clone https://github.com/fabien-ors/swig.git
      cd swig
      $env:PATH="${{env.BISON_ROOT}}\Bison.3.7.4\bin;" + $env:PATH
      $PCRE_PATH="${{env.PCRE2_ROOT}}\PCRE2.10.39.0"
      cmake -B${{env.BUILD_DIR}} -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX:PATH=${{env.SWIG_ROOT}} -DCMAKE_C_FLAGS="/DPCRE2_STATIC" -DCMAKE_CXX_FLAGS="/DPCRE2_STATIC" -DPCRE2_INCLUDE_DIR="$PCRE_PATH/include" -DPCRE2_LIBRARY="$PCRE_PATH/lib/pcre2-8-static.lib"
      cmake --build ${{env.BUILD_DIR}} --config Release
      cmake --install ${{env.BUILD_DIR}} --config Release
