name: install-swig-r-windows
description: "Install SWIG from source under windows using RTools (MingGw/MSYS2)."
author: 'Fabien Ors'

inputs:
  swig-root:
    description: 'SWIG installation directory'
  swig-repo:
    description: 'SWIG git repository (must be called "swig")'
    default: "https://github.com/fabien-ors/swig"
  swig-tag:
    description: 'SWIG tag on the repository (TODO)'
    default: "4.2.0b"
  bison-version:
    description: 'Version for Bison library'
    default: "3.8.2-5"
  pcre2-version:
    description: 'Version for PCRE2 library'
    default: "10.42-1"
  
runs:
  using: "composite"
  steps:

  - name: Install SWIG dependencies
    shell: msys2 {0}
    run: |
      pacman -Sy "bison=${{inputs.bison-version}}"
      pacman -Sy "mingw-w64-x86_64-pcre2=${{inputs.pcre2-version}}"

  - name: Compile and install [customized] SWIG
    shell: msys2 {0}
    # TODO : Use swig-tag variable (not the master branch)
    run: |
      mkdir swig_src
      cd swig_src
      git clone ${{inputs.swig-repo}}
      cd swig
      cmake -Bbuild -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=${{inputs.swig-root}}
      cmake --build build --config Release
      cmake --install build --config Release