name: coverage-tests

on:
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  call-coverage-tests_python:
    uses: ./.github/workflows/coverage-tests_python.yml
  call-coverage-tests_r:
    uses: ./.github/workflows/coverage-tests_r.yml
    
