name: dry-test_r

on:
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        r_version: ["4.0.5","4.1.3","4.2.3","4.3.2"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r_version}}

    - name: Install swigex0
      run: Rscript -e "install.packages(c('swigex0'), repos='https://soft.mines-paristech.fr/cran/', dependencies = TRUE)"

    - name: Run the r test
      run: Rscript tests/r/testFibo.r
      