name: nonreg-tests_macos-latest

on:
  # Permit calling trigger
  workflow_call:
  # Activate the workflow at each push on test_features branch
  push:
    branches: [ test_features ]
  # Activate the workflow at each pull request on main branch
  #pull_request:
  #  branches: [ main ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  EIGEN_ROOT : ${{github.workspace}}/eigen
  EIGEN_VERSION : "3.4.0"
  
jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: brew install llvm

  - name : Download, uncompressed and install Eigen headers
    shell: bash
    run: |
      EIGEN_URL="https://gitlab.com/libeigen/eigen/-/archive/${{env.EIGEN_VERSION}}/eigen-${{env.EIGEN_VERSION}}.zip"
      mkdir ${{env.EIGEN_ROOT}}
      mkdir eigen_src
      curl --progress-bar --location --output eigen_src/download.zip $EIGEN_URL
      7z -oeigen_src x eigen_src/download.zip -y -bd
      cd eigen_src
      cd eigen-*
      cmake -Bbuild -DCMAKE_INSTALL_PREFIX="${{env.EIGEN_ROOT}}" -DCMAKE_Fortran_COMPILER=""
      cmake --build build --target install

    - name: Run check from Makefile
      run: make check_cpp
