name: nonreg-tests_windows-2019-msvc

on:
  # Deactivate the workflow
  #push:
  #  branches-ignore:
  #    - '**'
  # Activate the workflow at each push on main branch
  push:
    branches: [ main ]
  # Activate the workflow at each pull request on main branch
  pull_request:
    branches: [ main ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR : build
  PYTHON_VERSION : "3.11"
  COMPILE_VERSION : '"Visual Studio 16 2019"' #Because cmake -G needs " "
  #SWIG_ROOT : ${{github.workspace}}/swig_420b

jobs:
  
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python Version
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install Python dependency
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy

    - name: Configure cmake
      run: cmake -B${{env.BUILD_DIR}} -G ${{env.COMPILE_VERSION}} -DBUILD_PYTHON=ON

    - name: Compile, install packages and execute non-regression tests
      # Execute tests defined by the CMake configuration.
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --target check
