name: nonreg-tests_macos-latest2

on:
  # Permit calling trigger
  workflow_call:
  # Activate the workflow at each push on test_features branch
  push:
    branches: [ test_features ]
  # Activate the workflow at each pull request on main branch
  #pull_request:
  #  branches: [ main ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  PYTHON_VERSION : "3.11"
  NUMPY_VERSION : "1.23.5"
  R_VERSION : "4.3.2"
  SWIG_ROOT : ${{github.workspace}}/swig_420b
  EIGEN_ROOT : ${{github.workspace}}/eigen
  EIGEN_VERSION : "3.4.0"

jobs:
  build:
    runs-on: ${{matrix.arch.os}}
    strategy:
      matrix:
        python: [
          # Double quote for version is needed otherwise 3.10 => 3.1
            {py: "3.8",  nu: 1.20.3},
            {py: "3.9",  nu: 1.20.3},
            {py: "3.10", nu: 1.21.6},
            {py: "3.11", nu: 1.23.5},
            {py: "3.12", nu: 1.26.3}
          ]
        arch: [
            {ar: x86_64, os: macos-12, pat: /usr/local},
            {ar: arm64,  os: macos-14, pat: /opt/homebrew}
          ]
        exclude:
          - arch: {ar: arm64}
            python: {py: "3.8"}
          - arch: {ar: arm64}
            python: {py: "3.9"}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: brew install llvm
      
    - name: Setup Python Version
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python.py}}

    - name: Install numpy
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy==${{matrix.python.nu}}

    - name : Download, uncompressed and install Eigen headers
      shell: bash
      run: |
        EIGEN_URL="https://gitlab.com/libeigen/eigen/-/archive/${{env.EIGEN_VERSION}}/eigen-${{env.EIGEN_VERSION}}.zip"
        mkdir ${{env.EIGEN_ROOT}}
        mkdir eigen_src
        curl --progress-bar --location --output eigen_src/download.zip $EIGEN_URL
        7z -oeigen_src x eigen_src/download.zip -y -bd
        cd eigen_src
        cd eigen-*
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX="${{env.EIGEN_ROOT}}" -DCMAKE_Fortran_COMPILER=""
        cmake --build build --target install

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{env.R_VERSION}}

    - name: Install the customized SWIG from source
      uses: fabien-ors/install-swig-unix-action@v1
      with:
        swig-root: ${{env.SWIG_ROOT}}
        generator: "Unix Makefiles"

    - name: Configure CMake
      run: CC=${{matrix.arch.pat}}/opt/llvm/bin/clang CXX=${{matrix.arch.pat}}/opt/llvm/bin/clang++ cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_PYTHON=ON -DBUILD_R=ON -DSWIG_EXECUTABLE=${{env.SWIG_ROOT}}/bin/swig -DEigen3_ROOT=${{env.EIGEN_ROOT}}

    - name: Compile, install packages and execute non-regression tests
      run: cmake --build ${{env.BUILD_DIR}} --target check