name: publish_r_ubuntu-16

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fabienors/test_ubuntu-16

    steps:
    - uses: actions/checkout@v3

    - name: Setup personal R libraries directory
      # Beware : ~/ is Linux only. For a potential windows a solution must be found
      run: mkdir -p ~/r_libs & echo ".libPaths('~/r_libs')" > ~/.Rprofile

    - name : Create Package
      run : |
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DBUILD_R=ON -DBUILD_PYTHON=OFF
        cmake --build ${{env.BUILD_DIR}} --target r_install

    - name: Upload to CG CRAN-like (OVH)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CG_HOST }}
        username: ${{ secrets.CG_USR }}
        password: ${{ secrets.CG_PWD }}
        source: ${{env.BUILD_DIR}}/r/${{env.BUILD_TYPE}}/swigex0*.tar.gz
        target: /var/www/html/cran/src/contrib/
        strip_components: 3

    - name: Updating CG CRAN-like index
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.CG_HOST }}
        username: ${{ secrets.CG_USR }}
        password: ${{ secrets.CG_PWD }}
        script: cd /var/www/html/cran && Rscript -e 'tools::write_PACKAGES("src/contrib/", type="source")'
