name: publish_python_ubuntu

on:
  # Permit calling the workflow from outside (https://github.com/actions/runner/discussions/1884)
  workflow_call:
    inputs:
      external_call:
        description: 'To distinguish workflow_call from other events'
        type: boolean
        required: false
        default: true
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''
      external_call:
        description: 'To distinguish workflow_call from other events'
        type: boolean
        required: false
        default: false

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  BUILD_PLAT: manylinux1_x86_64
  EIGEN_ROOT : ${{github.workspace}}/eigen
  EIGEN_VERSION : "3.4.0"
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # Corresponding docker file comes from:
      # https://github.com/fabien-ors/docker-generate
      image: fabienors/ubuntu-16-swigex0
    strategy:
      matrix:
        python: [py38, py39, py310, py311, py312]

    steps:
    - uses: actions/checkout@v3

    - name : Download, uncompressed and install Eigen headers
      shell: bash
      run: |
        EIGEN_URL="https://gitlab.com/libeigen/eigen/-/archive/${{env.EIGEN_VERSION}}/eigen-${{env.EIGEN_VERSION}}.zip"
        mkdir ${{env.EIGEN_ROOT}}
        mkdir eigen_src
        curl --progress-bar --location --output eigen_src/download.zip $EIGEN_URL
        7z -oeigen_src x eigen_src/download.zip -y -bd
        cd eigen_src
        cd eigen-*
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX="${{env.EIGEN_ROOT}}" -DCMAKE_Fortran_COMPILER=""
        cmake --build build --target install

    - name : Create Wheels
      run : |
        export PATH=/opt/python/${{matrix.python}}/bin:$PATH
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DBUILD_PYTHON=ON -DEigen3_ROOT=${{env.EIGEN_ROOT}}
        cmake --build ${{env.BUILD_DIR}} --target python_build
        cd ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}
        # Note: wheel must be declared not pure (see setup.py)
        python3 setup.py bdist_wheel --plat-name=${{env.BUILD_PLAT}}

    - name : Upload
      run : |
        export PATH=/opt/python/${{matrix.python}}/bin:$PATH
        python3 -m twine upload --verbose ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.TWINE_PYPI_PWD}}
        TWINE_REPOSITORY: pypi

   

