name: publish_python_windows-2019_macos-11

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, macos-11]

    steps:
    - uses: actions/checkout@v4

    # Needed for macos-13 runner
#    - name : Install SWIG
#      run: brew install swig
      
    # Explicit Python version needed for having env.pythonLocation
    # because error locating python on MacOS : https://github.com/actions/setup-python/issues/121
    - name: Setup Python Version
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install twine
        python -m pip install numpy==1.26.4
        python -m pip install cibuildwheel==2.16.5

    - name : Compile python package
      run : |
        cmake -Bbuild-${{matrix.os}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DPython3_ROOT_DIR="${{env.pythonLocation}}" -DBUILD_PYTHON=ON
        cmake --build build-${{matrix.os}} --target python_build --config ${{env.BUILD_TYPE}}

    - name: Build wheels
      run: |
        cd build-${{matrix.os}}/python/${{env.BUILD_TYPE}}
        python -m cibuildwheel --output-dir wheelhouse
        ls wheelhouse

    - name : Upload
      run : python -m twine upload build-${{matrix.os}}/python/${{env.BUILD_TYPE}}/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.TWINE_PYPI_PWD}}
        TWINE_REPOSITORY: pypi
