name: publish_r_ubuntu-16

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # Corresponding docker file comes from:
      # https://github.com/fabien-ors/docker-generate
      image: fabienors/test_ubuntu-16

    steps:
    - uses: actions/checkout@v3

    - name: Build the package and save generated file name in the environment
      run: |
        export PATH=/opt/r/${{matrix.r}}/bin:$PATH
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DBUILD_R=ON -DBUILD_PYTHON=OFF
        cmake --build ${{env.BUILD_DIR}} --target r_install
        echo "MY_PKG=$(ls ${{env.BUILD_DIR}}/r/${{env.BUILD_TYPE}}/swigex0_*.tar.gz)" >> "$GITHUB_ENV"

    - name: Result message
      run: echo "Built ${{ env.MY_PKG }}"

    - uses: actions/upload-artifact@v3 
      with:
        name: ubuntu-package
        path: ${{ env.MY_PKG }}

  publish:
    needs: build
    # Only ubuntu can upload to CRAN easily (ssh)
    runs-on: ubuntu-latest
    
    steps:
    - uses: fabien-ors/cran-publish-action@v9
      with:
        host: ${{ secrets.CG_HOST }}
        username: ${{ secrets.CG_USR }}
        password: ${{ secrets.CG_PWD }}
        repo-path: "/var/www/html/cran"
