name: publish_r_macos-11

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  SWIG_ROOT  : ${{github.workspace}}/swig_420b

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy :
      matrix:
        # Last release from here https://cran.r-project.org/src/base/R-4/
        r_version: ["4.3.2"]
        os: [macos-11]
        
    steps:
    - uses: actions/checkout@v3

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r_version}}

    - name: Compile and install [customized] SWIG 4.2.0b
      # TODO : Use a tagged realease (not the master branch)
      run: |
        mkdir swig_src
        cd swig_src
        git clone https://github.com/fabien-ors/swig.git
        cd swig
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX:PATH=${{env.SWIG_ROOT}}
        cd build
        make
        make install

    - name : Build the package and save generated file name in the environment
      run : |
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DBUILD_R=ON -DBUILD_PYTHON=OFF -DSWIG_EXECUTABLE=${{env.SWIG_ROOT}}/bin/swig
        cmake --build ${{env.BUILD_DIR}} --target r_install
        echo "MY_PKG=$(ls ${{env.BUILD_DIR}}/r/${{env.BUILD_TYPE}}/swigex0_*.tgz)" >> "$GITHUB_ENV"

    - uses: actions/upload-artifact@v3
      # Use specific artifact identifier for publishing all R versions
      with:
        name: macos-package-${{matrix.r_version}}
        path: ${{env.MY_PKG}}
    
  publish:
    needs: build
    # Only ubuntu can upload via ssh
    runs-on: ubuntu-latest
    
    steps:
    - uses: fabien-ors/cran-publish-action@v1
      with:
        host: ${{secrets.CG_HOST}}
        username: ${{secrets.CG_USR}}
        password: ${{secrets.CG_PWD}}
        repo-path: "/var/www/html/cran"

    # Delete the artifacts (for freeing storage space under github)
    - uses: geekyeggo/delete-artifact@v2
      with:
        name: macos-package-*

