name: test_publish

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''


jobs:
  build:
    runs-on: windows-2019

    steps:
    - run: Set-Content -Path world_win.txt -Value "hello"
      shell: pwsh
      
    - uses: actions/upload-artifact@v3 
      with:
        name: win-package
        path: world_win.txt

  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: win-package
        
    - run: |
       ls
       test_val="$(ls)"
       echo "File read: $test_val"
