name: test_publish

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''


jobs:
  build:
    runs-on: windows-2019

    steps:
    - run: |
        Set-Content -Path world_win.txt -Value "hello"
        $dir = .txt
        $myfile = Get-ChildItem -Path $dir -File
      shell: pwsh
      
    - uses: actions/upload-artifact@v3 
      with:
        name: win-package
        path: $myfile

  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: win-package
        
    - name: ls 1
      run: |
       ls
       echo "test_val=$(ls *.txt)" >> "$GITHUB_ENV"
       echo "File read: ${{ env.test_val }}"

    - name: ls 2
      run: |
       ls
       echo "Environment variable is: ${{ env.test_val }}"