name: test_publish

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''


jobs:
  build:
    runs-on: windows-2019
    strategy :
      matrix:
        who-to-greet: ["Joe","Peter"]

    steps:
    - run: |
        Set-Content -Path world_win_${{matrix.who-to-greet}}.txt -Value "hello ${{matrix.who-to-greet}}"
        $file_list = Get-ChildItem -Path "./" -File
        echo "myfile=$file_list" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
      
    - uses: actions/upload-artifact@v3 
      with:
        name: win-package
        path: ${{ env.myfile }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v3
      with:
#        name: win-package
        path: download_artifacts
        
    - name: List artifacts and create environment variable
      run: |
       ls -ls download_artifacts/*
       flist=$(ls download_artifacts/*/*.txt)
       echo "flist is: $flist"
       echo "test_val='$flist'" >> "$GITHUB_ENV"
       echo "Environment variable is: ${{ env.test_val }} (nothing display here)"

    - name: Show environment variable
      run: |
        echo "Environment variable is: ${{ env.test_val }}"
      